// projects.ts

export type TagType = "live" | "type" | "status" | string;

export interface Tag {
  label: string;
  type: TagType;
}

export interface Feature {
  title: string;
  desc: string;
}

export interface Metric {
  value: string;
  label: string;
  highlight: boolean;
}

export type ProjectStatus = "Production" | "Development" | "Archived" | string;
export type ProjectCategory = "Machine Learning" | "WebApp" | "AI" | "Backend" | string;
export type ProjectType = "Backend System" | "Frontend App" | "Full Stack" | string;
export type DiagramType = string;

export interface Project {
  id: string;
  num: string;
  name: string;
  category: ProjectCategory;
  href: string;
  image: string;
  status: ProjectStatus;
  year: string;
  role: string;
  type: ProjectType;
  impact: string;
  duration: string;
  sub: string;
  tags: Tag[];
  overview: string;
  problem: string;
  challenges: string[];
  decisions: string[];
  features: Feature[];
  stack: string[];
  metrics: Metric[];
  githubUrl: string;
  demoUrl: string;
  diagramType: DiagramType;
}

export const projects: Project[] = [
    {
    id: "news-scraper-lead-engine",
    num: "01",
    name: "News Scraper & Lead Intelligence Engine",
    category: "AI / Data Engineering",
    href: "/projects/news-scraper-lead-engine",
    image: `${process.env.NEXT_PUBLIC_CDN_URL}/news_scraper.png`,
    status: "Production",
    year: "2024",
    role: "Backend & ML Engineer",
    type: "Automation Pipeline",
    impact:
      "Replaces manual business-development research across 16 Indian news outlets with a fully automated pipeline — extracting structured lead intelligence from hundreds of articles per run without human intervention.",
    duration: "6 months",
    sub: "Built an async Python pipeline that aggregates business news from RSS feeds and Vertex AI Search, scrapes articles via Tor, classifies leads with Bedrock LLMs, enriches company data, performs semantic deduplication using embeddings, and stores structured results in PostgreSQL.",
    tags: [
      { label: "Live", type: "live" },
      { label: "AI / LLM", type: "type" },
      { label: "Web Scraping", type: "type" },
    ],
    overview:
      "A fully automated, asynchronous news-intelligence pipeline built in Python. It ingests articles from 20 RSS feeds (The Hindu, Zee News, Hindustan Times, India TV, Times of India, ET Now, Indian Express, PR Newswire) and Google Vertex AI Discovery Search. Each article is full-text scraped via a Tor hidden-service API, then passed through a two-stage AWS Bedrock (Nova Lite) LLM pipeline: first to classify whether it is a business lead, then to extract structured entities (companies, contacts, signals, project details). Confirmed leads are enriched with LinkedIn data via Unipile. Article summaries and categories are generated by Bedrock, keywords by YAKE. Every article summary is embedded with Alibaba-NLP/gte-large-en-v1.5 (1024-dim) and stored in a pgvector store in PostgreSQL to detect semantically similar prior coverage. Results are fanned out across a normalised 14-table schema.",
    problem:
      "Business development teams spend hours every day manually scanning dozens of Indian news outlets to find companies announcing funding rounds, tech initiatives, and leadership changes — events that represent actionable sales or partnership opportunities. The process is slow, non-scalable, and produces unstructured output that is hard to act on.",
    challenges: [
      "Reliable full-text scraping across news sites with varied anti-bot measures — solved with a Tor-routed onion-service scraper that classifies SOCKS errors (TTL expiry 0x06, host-down 0x01, connection refused 0x05) and auto-restarts the Tor circuit only when genuinely needed.",
      "Semantic deduplication across a growing article store without an O(n²) comparison — solved by embedding each summary (1024-dim) and running a threshold cosine-similarity query directly in PostgreSQL via pgvector.",
      "Extracting structured JSON (companies, contacts, project details) from unstructured LLM output reliably — Pydantic validation is enforced at parse time on every Bedrock response, with graceful fallback defaults.",
      "Long news articles that exceed the sentence-transformer's safe token window — solved with overlapping chunking and re-normalised embeddings across all chunks.",
      "Coordinating async DB pool lifecycle, port binding, and graceful shutdown across a single-process asyncio app — handled with a singleton DatabaseManager with exponential-backoff retry and a dedicated port-lock socket.",
    ],
    decisions: [
      "Tor onion-service (SOCKS5h) over direct scraping — eliminates per-request billing and reduces TLS fingerprinting exposure.",
      "Two-stage LLM calls (classify → extract) rather than one — saves tokens on the ~60% of articles that are not leads; the extraction stage only fires for confirmed leads.",
      "Amazon Bedrock (Nova Lite) over OpenAI — reuses existing AWS IAM/credential infrastructure and keeps all data within the AWS boundary.",
      "PostgreSQL + pgvector over a dedicated vector store (Pinecone/Weaviate) — keeps lead metadata and vectors co-located, eliminates a network hop, and allows JOIN-based retrieval.",
      "YAKE (unsupervised keyword extraction) for article keywords — zero latency, zero cost, sufficient quality for downstream tagging.",
    ],
    features: [
      { title: "Dual-source Ingestion", desc: "Collects articles from 20 RSS feeds across 16 Indian news outlets and from Google Vertex AI Discovery Search using configurable search terms stored in PostgreSQL. Both sources write to the same flat JSON staging file with deduplication." },
      { title: "Tor-routed Full-text Scraping", desc: "Routes each article URL through a remote onion-service scraper API. Distinguishes TTL-expiry (0x06), host-down (0x01), and unreachable (0x04) SOCKS errors, applies targeted retry/circuit-restart logic per error class, and records scraper diagnostics in the DB for monitoring." },
      { title: "Two-stage LLM Lead Pipeline", desc: "Stage 1 (classification): Bedrock Nova Lite determines whether the article is a business lead, returning confidence (HIGH/MEDIUM/LOW) and structured reasons. Stage 2 fires only for confirmed leads — extracting companies, contacts, business signals, project details, funding sources, and stated goals." },
      { title: "Unipile Company Enrichment", desc: "For each extracted company, Unipile is queried to resolve LinkedIn profile URL, logo, website, employee count range, and headquarters city/country. Enriched data is merged into the company record before DB insertion." },
      { title: "Semantic Deduplication with pgvector", desc: "Each confirmed-lead article summary is embedded with Alibaba-NLP/gte-large-en-v1.5 (1024-dim). The embedding is compared against all existing vectors in PostgreSQL via pgvector cosine similarity; near-duplicate articles are stored as 'similar' rather than 'unique'." },
      { title: "Normalised 14-table PostgreSQL Schema", desc: "Articles fan out across primary, main, full-news, vectors, category, keywords, and search-term tables — plus leads-summary, lead-companies, lead-contacts, lead-signals, lead-projects, processed, and failed tables — enabling granular querying and per-stage failure tracking." },
    ],
    stack: ["Python 3.11", "asyncio", "Pydantic v2", "asyncpg", "PostgreSQL", "pgvector", "Amazon Bedrock (Nova Lite)", "Sentence Transformers — GTE-Large-en-v1.5", "Tor / SOCKS5h", "YAKE", "feedparser", "Google Vertex AI Discovery Search", "Unipile API", "AWS Secrets Manager", "python-dotenv", "filelock", "pytz"],
    metrics: [
      { value: "16",      label: "News Sources Integrated",              highlight: true  },
      { value: "20",      label: "RSS Feeds Monitored",                  highlight: false },
      { value: "1024",    label: "Vector Embedding Dimensions",          highlight: false },
      { value: "2-stage", label: "LLM Pipeline Architecture",            highlight: true  },
      { value: "14",      label: "Normalised DB Tables",                 highlight: false },
      { value: "100+",    label: "Articles Processed per Engine Run",    highlight: false },
    ],
    githubUrl: "https://github.com/avneeshrai07/NEWS_SCRAPER_new",
    demoUrl: "https://github.com/avneeshrai07/NEWS_SCRAPER_new",
    diagramType: "pipeline",
  },
  {
    id: "optibuild-python",
    num: "02",
    name: "OptiBuild",
    category: "Structural Engineering Automation",
    href: "/projects/optibuild-python",
    image: `${process.env.NEXT_PUBLIC_CDN_URL}/optibuild.png`,
    status: "Production",
    year: "2025",
    role: "Backend Engineer",
    type: "REST API / Automation Engine",
    impact:
      "Reduces manual STAAD.Pro model creation from hours to seconds for portal-frame industrial steel buildings, enabling engineers to iterate on building designs instantly.",
    duration: "1 year",
    sub: "Flask REST API that auto-generates STAAD.Pro command files and Excel calculation sheets for industrial steel buildings using Indian and American load codes.",
    tags: [
      { label: "Live", type: "live" },
      { label: "Flask API", type: "type" },
    ],
    overview:
      "OptiBuild is a Python/Flask REST API that automates the generation of STAAD.Pro structural analysis models for portal-frame industrial steel buildings. An engineer POSTs parametric building data — dimensions, roof type, bay layout, and wind/seismic parameters — and receives back a complete STAAD command file plus an Excel calculation sheet. The system supports both 3D full-building models (/submit) and 2D cross-section frames (/submit_2D), running Flask 3.1.1 deployed as a systemd service on AWS.",
    problem:
      "Structural engineers spend hours hand-authoring STAAD.Pro input files for every new portal-frame building project. The geometry, member connectivity, and load combinations must be recalculated from scratch each time, making the process slow, error-prone, and hard to standardise across a team.",
    challenges: [
      "Computing accurate 3D node coordinates for compound configurations: offset apex, internal columns (IC), canopies, cranes, and mezzanines — each adding new geometry layers.",
      "Supporting both Indian (IS 875 / IS 1893) and American (ASCE 7) wind and seismic load code pathways with differing pressure factors, importance factors, and terrain categories.",
      "Handling fully dynamic bay spacing where each sidewall and endwall bay can have a different width, while keeping node indexing consistent.",
      "Designing a composable NodeMaker → MemberMaker → StaadProcessor pipeline so optional features (cranes, canopies, mezzanines) can be toggled independently without breaking the rest of the model.",
      "Providing actionable structured error responses that distinguish input-validation failures from runtime errors, and persisting full context (inputs + traceback) to AWS S3 for post-mortem analysis.",
    ],
    decisions: [
      "Flask over FastAPI — dependency-minimal on the self-hosted runner, matching the team's existing Python toolchain.",
      "Geometry separated into discrete NodeMaker sub-packages (ground, eve, apex, brick, IC, canopy, crane, mezz, roof-monitor, cross-bracing) so each segment is independently testable and composable.",
      "openpyxl for Excel output alongside the STAAD command file — matches the sign-off workflow engineers already use for design review.",
      "boto3 + AWS S3 to persist error logs and output files — multi-user concurrent access with no file contention on the server.",
      "GitHub Actions → self-hosted runner → systemd restart on every push to main — continuous delivery without a container layer.",
    ],
    features: [
      { title: "3D & 2D Model Generation", desc: "Two endpoints — /submit for full 3D STAAD models and /submit_2D for 2D portal-frame cross-sections — sharing the same parametric input schema." },
      { title: "Multi-Roof Type Support", desc: "Handles gable and offset-apex roof geometries with per-side configurable slopes and custom apex positions." },
      { title: "Composable Structural Add-ons", desc: "Canopies, overhead cranes, mezzanine floors, internal columns (IC), and roof monitors are optional features that stack cleanly onto any base building." },
      { title: "Dual Load Code Engine", desc: "Full Indian (IS 875 / IS 1893) and American (ASCE 7) wind, seismic, and load-combination pathways, selectable per request via calculation_type." },
      { title: "Dynamic Bay Spacing", desc: "Accepts uniform or fully custom bay-width arrays for sidewalls and endwalls independently, with automatic cross-bracing layout adjustment." },
      { title: "Excel Calculation Sheet Output", desc: "Produces a structured openpyxl workbook alongside the STAAD command text so engineers can review calculations without leaving their existing tools." },
      { title: "Structured Error Reporting", desc: "Returns typed JSON error responses distinguishing InputError (400) from runtime failures (500), with full inputs and tracebacks written to timestamped log files on AWS S3." },
    ],
    stack: ["Python", "Flask", "NumPy", "Pandas", "openpyxl", "boto3 / AWS S3", "Gunicorn", "GitHub Actions", "systemd"],
    metrics: [
      { value: "50+",   label: "Buildings Generated",                  highlight: false },
      { value: "3.1.1", label: "Production API Version",               highlight: false },
      { value: "2",     label: "Structural Codes (Indian & American)",  highlight: true  },
      { value: "< 5s",  label: "Full 3D Model Generation Time",        highlight: true  },
    ],
    githubUrl: "https://github.com/abhinav-tyagi03/optibuild-python",
    demoUrl: "https://optibuild.orbitaim.io/",
    diagramType: "architecture",
  },
  {
    id: "cold-email-python-orbit",
    num: "03",
    name: "Orbit Cold Mailer",
    category: "AI Automation",
    href: "/projects/cold-email-python-orbit",
    image: `${process.env.NEXT_PUBLIC_CDN_URL}/cold_email.png`,
    status: "Production",
    year: "2025",
    role: "Backend Engineer",
    type: "AI SaaS API",
    impact:
      "Eliminates manual prospect research by autonomously generating hyper-personalized cold emails, LinkedIn messages, and WhatsApp messages using real-time data — covering all outreach channels from a single API call.",
    duration: "6 months",
    sub: "AI-powered B2B cold outreach engine that researches prospects in real-time and generates personalized emails, LinkedIn messages, and WhatsApp messages via a production FastAPI backend.",
    tags: [
      { label: "Production", type: "live" },
      { label: "FastAPI", type: "type" },
      { label: "Python", type: "type" },
      { label: "Gemini 2.5", type: "type" },
    ],
    overview:
      "Orbit Cold Mailer is a production FastAPI backend that orchestrates multi-channel B2B cold outreach. It ingests buyer profiles and seller context, runs AI research using Tavily web search and LinkedIn post analysis, and generates hyper-personalized cold emails, LinkedIn messages, WhatsApp messages, and follow-up emails — each on its own dedicated route. The system supports multiple LLM backends (Gemini Flash, OpenAI GPT, AWS Bedrock) behind a unified router and streams real-time research progress via WebSocket.",
    problem:
      "Sales teams spend hours researching a prospect only to send a cold email that still ends up generic. There is no scalable way to produce outreach that references a prospect's real recent activity, business pain points, and company-specific context while staying concise, natural, and conversion-focused across email, LinkedIn, and WhatsApp.",
    challenges: [
      "Orchestrating multi-step AI research (LinkedIn analysis, company insights) inside a single API request without hitting timeout limits.",
      "Supporting Gemini, GPT, and AWS Bedrock with transparent failover so prompts never need to change across providers.",
      "Managing 12 Tavily API keys with automatic rotation to prevent rate-limit failures during high traffic.",
      "Streaming incremental research progress in real-time via WebSocket while async pipeline tasks run concurrently.",
      "Mapping heterogeneous buyer/seller input into a strict Pydantic model before passing to the LLM pipeline.",
      "Preventing hallucinations in generation — only facts explicitly present in the prompt may appear in the output.",
    ],
    decisions: [
      "FastAPI over Flask — native async/await support enables concurrent research tasks without thread-pool overhead.",
      "Pydantic models at every layer — input validation, LLM structured output, and company insights — for end-to-end type safety.",
      "LLM router abstraction built so Gemini, GPT, and Bedrock are interchangeable without touching any prompt or business logic.",
      "Tavily multi-key pool implemented as an ordered failover list so one exhausted key never blocks a live request.",
      "WebSocket route added alongside REST endpoints to push each research step to the client without polling.",
      "Email prompt engineered with an explicit no-hallucination rule so the model can only use data provided in the context.",
    ],
    features: [
      { title: "Cold Email Generation", desc: "Generates personalized B2B cold emails via /cold-email with AI-researched buyer context, banned-word enforcement, and a strict no-hallucination guarantee." },
      { title: "LinkedIn Message Generation", desc: "Produces concise sub-500-character messages via /cold-message, tailored to the buyer's profile and recent company activity." },
      { title: "WhatsApp Message Generation", desc: "Creates WhatsApp-ready outreach via /cold-whatsapp using the same research-first pipeline as cold email." },
      { title: "Follow-up Email Engine", desc: "Generates contextual follow-ups via /followup that reference the original subject and body for thread continuity." },
      { title: "Real-time WebSocket Streaming", desc: "Pushes each research step as a live chunk to the client over WebSocket so the UI updates while the pipeline is still running." },
      { title: "Multi-LLM Router", desc: "Unified abstraction routing to Gemini Flash, OpenAI GPT, or AWS Bedrock with automatic failover between providers." },
      { title: "Tavily Web Research with Key Pooling", desc: "Runs date-scoped advanced web searches using a 12-key Tavily pool — failed keys are skipped automatically so research never stalls." },
      { title: "LinkedIn Insight Extraction", desc: "Parses buyer and company LinkedIn activity to extract buying intent, opportunities, sentiment, writing style, and mentioned technologies." },
    ],
    stack: ["Python", "FastAPI", "Pydantic", "Google Gemini 2.5 Flash", "OpenAI GPT", "AWS Bedrock", "LangChain", "Tavily", "PostgreSQL", "asyncpg", "WebSocket", "uvicorn"],
    metrics: [
      { value: "4",  label: "Outreach Channels (Email, LinkedIn, WhatsApp, Follow-up)", highlight: true  },
      { value: "12", label: "Tavily API Keys in Rotation",                               highlight: false },
      { value: "3",  label: "LLM Providers Supported (Gemini, GPT, Bedrock)",            highlight: true  },
      { value: "5",  label: "Async Research Steps per Request",                          highlight: false },
    ],
    githubUrl: "https://github.com/avneeshrai07/cold-email-python-orbit",
    demoUrl: "https://github.com/avneeshrai07/cold-email-python-orbit",
    diagramType: "flowchart",
  },
  {
    id: "orbit-python-data",
    num: "04",
    name: "Orbit Python Data API",
    category: "Backend / Data Infrastructure",
    href: "/projects/orbit-python-data",
    image: `${process.env.NEXT_PUBLIC_CDN_URL}/orbit_data_python.png`,
    status: "Production",
    year: "2025",
    role: "Backend Engineer",
    type: "B2B Lead Intelligence API",
    impact:
      "Powers real-time lead enrichment and prospect search for sales teams across a PostgreSQL warehouse of email-to-LinkedIn mapped records.",
    duration: "6+ months",
    sub: "A production FastAPI microservice that serves B2B lead and company data from a PostgreSQL warehouse, with AWS CloudWatch logging and on-demand LinkedIn scraping.",
    tags: [
      { label: "Live", type: "live" },
      { label: "FastAPI", type: "type" },
    ],
    overview:
      "orbit-python-data is the data backbone for B2B prospecting. It queries a PostgreSQL warehouse of lead profiles (email-to-LinkedIn mapped) and company profiles, supports multi-filter paginated search across 8 dimensions, and enriches company data on cache miss via an external LinkedIn scraper microservice. Structured JSON logs are shipped to AWS CloudWatch with IST timestamps for auditability. Secrets are loaded from AWS Secrets Manager at startup. Deployed to a self-hosted runner via GitHub Actions.",
    problem:
      "Sales teams needed a fast, filterable API to retrieve and enrich B2B leads from a large PostgreSQL warehouse of email-to-LinkedIn mapped records, while also resolving and enriching company profiles on demand — without hitting the scraper redundantly for domains already stored in the local database.",
    challenges: [
      "Managing an async asyncpg connection pool safely across a high-concurrency FastAPI app, including health checks and exponential-backoff retry on startup failure.",
      "Preventing duplicate company inserts from concurrent requests before the first insert completes.",
      "Building a single parameterized SQL query supporting up to 8 optional filter dimensions (LinkedIn URL, email, name, country, domain, job title, company name, employee count, industry) without SQL injection risk.",
      "Shipping structured JSON logs with IST timestamps while stripping invalid UTF-16 surrogate codepoints and never letting a logging failure crash the application.",
      "Integrating an external scraper microservice with graceful error propagation when the scraper returns 504/505 status codes.",
    ],
    decisions: [
      "asyncpg pool with a singleton DatabaseManager protected by an asyncio.Lock to prevent pool duplication under concurrent lifespan startup.",
      "Raw parameterized queries with a manual $N counter instead of an ORM — full control over generated SQL and no N+1 risks on JOINs.",
      "DB-first, scrape-second, insert-third flow in /get_basicCompanyDetails to avoid redundant scraper calls for already-stored domains.",
      "SafeJSONFormatter that delegates IST time formatting and strips surrogates before json.dumps, so logs are always valid UTF-8 JSON in CloudWatch.",
      "All secrets (DB credentials, AWS keys) loaded from AWS Secrets Manager via boss_env.py before any dependent module import, rather than relying on environment variables.",
      "Redis caching and JWT auth middleware kept wired but commented out, so they can be re-enabled without structural changes when needed.",
    ],
    features: [
      { title: "Multi-filter Lead Search", desc: "POST /fetch_data_v2 accepts LinkedIn URL, email, name, country, domain, job title, company name, employee count range, and industry — all combinable, paginated (page/page_size), and safe against SQL injection via asyncpg parameterization." },
      { title: "On-demand Company Enrichment", desc: "POST /get_basicCompanyDetails checks the DB first; on a miss it calls the orbit-data scraper microservice, persists the enriched LinkedIn company profile, and returns it — deduplicating scraper calls for known domains." },
      { title: "Company Name Resolution", desc: "POST /get_company_by_name resolves fuzzy company names (case-insensitive) to structured LinkedIn profiles via DB lookup, falling back to the scraper and inserting new records automatically." },
      { title: "Filter Value Suggestions", desc: "POST /filter-values returns distinct values for filterable columns (company_name, job_title, industry, city, country, hashtags) to power autocomplete dropdowns in the frontend." },
      { title: "Universal Search", desc: "POST /universal_search performs a full-text keyword search across the leads warehouse with page/page_size pagination." },
      { title: "Async Connection Pool with Health Checks", desc: "DatabaseManager maintains an asyncpg pool (2–20 connections, statement_cache_size=1000) with active health checks (SELECT 1) and up to 5 exponential-backoff retries on startup." },
      { title: "Structured CloudWatch Logging", desc: "JSON logs with IST timestamps and full exception stacks are shipped to AWS CloudWatch log group logs/data_logger via a custom CloudWatchLogHandler that auto-refreshes sequence tokens." },
      { title: "AWS Secrets Manager Integration", desc: "boss_env.py pulls the prod/orbit secret bundle from AWS Secrets Manager at process startup, injecting DB credentials and API keys into the environment before any module that needs them is imported." },
    ],
    stack: ["Python 3.10", "FastAPI", "asyncpg", "PostgreSQL", "Pydantic v2", "aiohttp", "boto3 / AWS CloudWatch", "AWS Secrets Manager", "uvicorn", "redis[async]", "PyJWT", "psycopg2-binary", "GitHub Actions", "systemd"],
    metrics: [
      { value: "8",     label: "API Endpoints",                  highlight: false },
      { value: "20",    label: "Max DB Pool Connections",        highlight: true  },
      { value: "3",     label: "PostgreSQL Tables Queried",      highlight: false },
      { value: "60s",   label: "Scraper Request Timeout",        highlight: false },
      { value: "5",     label: "DB Startup Retry Attempts",      highlight: false },
      { value: "v2.2.5", label: "Current API Version",          highlight: true  },
    ],
    githubUrl: "https://github.com/abhinav-tyagi03/orbit-python-data",
    demoUrl: "https://orbit-data.miatibro.art",
    diagramType: "flowchart",
  },


];